version: '3.1'

services:
  data-monitoring:
    container_name: data-monitoring
    build: ./
    restart: "always"
    command: -u MY_ORANGE_USER -p MY_ORANGE_PASSWORD [--number MY_NUMBER_1] [--number MY_NUMBER_2]
